Repository himeshparashar/Social-Morph, pull requests merged in 2024-10, with the labels that each got.

#23 Added Dockerfile, .dockerignore file and the docker-compose.yml file
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#32 [ISSUE28] Improved Readme
  README.md
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#14 Added:: Missing Meta Tags for SEO Enhancement
  app/layout.tsx
  app/robots.ts
  app/sitemap.ts
  next-sitemap.config.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
Labels: hacktoberfest, gssoc-ext, level 1

#33 fix the alignment of dropdown content of features link on the navbar #30
  .dockerignore
  .env
  Dockerfile
  README.md
  app/dashboard/_components/Header.tsx
  app/dashboard/_components/SearchSection.tsx
  app/dashboard/_components/SideNav.tsx
  app/dashboard/_components/TemplateCard.tsx
  app/dashboard/_components/TemplateListSection.tsx
  app/dashboard/content/[template-slug]/page.tsx
  app/dashboard/content/_components/FormSection.tsx
  app/dashboard/content/_components/OutputSection.tsx
  app/dashboard/layout.tsx
  app/dashboard/page.tsx
  components/landing-page/Accordion.tsx
  components/landing-page/Footer.tsx
  components/landing-page/HeroContent.tsx
  components/landing-page/Infocards.tsx
  components/landing-page/Navbar.tsx
  components/landing-page/Testimonials.tsx
  docker-compose.yml
  package-lock.json
  package.json
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#56 Added Issue , Pull Request Templates and Github Actions
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-label.yml
  .github/workflows/greetings.yml
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#60 Created Templates for Issue and PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/ui_change.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#63 Enhancement : fixed TestimonialCards sizes and added HoverEffect
  components/landing-page/Testimonials.tsx
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#64 resolved accordion bug added logo
  components/landing-page/Accordion.tsx
  components/landing-page/Footer.tsx
  components/landing-page/Navbar.tsx
  docker-compose.yml
  utils/constants.js
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#66 Feature/implement a backend for Authorization
  .gitignore
  server/.gitignore
  server/@types/custom.d.ts
  server/README.md
  server/app.ts
  server/controllers/auth.controller.ts
  server/interfaces/tokenInterface.ts
  server/interfaces/userInterface.ts
  server/mails/activation-mail.ejs
  server/middleware/catchAsyncErrors.ts
  server/middleware/error.ts
  server/middleware/middleware.ts
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20241009120259_init/migration.sql
  server/prisma/migrations/20241009122537_init/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/routes/auth.route.ts
  server/server.ts
  server/tsconfig.json
  server/utils/ErrorHandler.ts
  server/utils/jwt.ts
  server/utils/redis.ts
  server/utils/sendMail.ts
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 3

#84 Changed the color of text and added color on hovering the icons
  components/landing-page/Footer.tsx
  package-lock.json
  package.json
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#109 Bug fix / Indexing of the dropdown
  components/landing-page/Navbar.tsx
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#130 Add transition to stats
  components/landing-page/Testimonials.tsx
  package-lock.json
  package.json
  utils/constants.js
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#133 Footer Fixed and enhanced
  components/landing-page/Footer.tsx
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 2

#97 Added the the pricing Page with proper linking in the navbar wiht sleek ui.
  app/pricing/page.tsx
  components/landing-page/Navbar.tsx
  components/ui/switch.tsx
  package-lock.json
  package.json
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 2

#98 Fixes #61: mobile view layout
  components/landing-page/Infocards.tsx
  components/landing-page/Navbar.tsx
  components/landing-page/Testimonials.tsx
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted

#121 Added animation and transition effects to faq & added the user button
  app/dashboard/page.tsx
  app/help/page.tsx
  app/notifications/page.tsx
  components/landing-page/Accordion.tsx
Labels: hacktoberfest, hacktoberfest-accepted, level 2

#137 dashboard ui fix
  app/dashboard/page.tsx
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 2

#116 #45 Unusual ui alignment
  components/landing-page/Infocards.tsx
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 1

#102 #83 Add Frontend for Signup/Signin
  app/(auth)/sign-in/[[...sign-in]]/page.tsx
  app/(auth)/sign-up/[[...sign-up]]/page.tsx
  app/dashboard/page.tsx
  app/help/page.tsx
  app/notifications/page.tsx
  app/pricing/page.tsx
  components/auth/Signin.tsx
  components/auth/Signup.tsx
  components/landing-page/Accordion.tsx
  components/landing-page/Footer.tsx
  components/landing-page/Infocards.tsx
  components/landing-page/Navbar.tsx
  components/landing-page/Testimonials.tsx
  components/ui/ButtonWarning.tsx
  components/ui/Heading.tsx
  components/ui/InputBox.tsx
  components/ui/SubHeading.tsx
  components/ui/switch.tsx
  package-lock.json
  package.json
  public/Placeholderimage.png
  server/prisma/migrations/20241016094201_init/migration.sql
  utils/constants.js
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, level 2

#149 made dashboard responsive
  app/dashboard/page.tsx
  package-lock.json
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#141 Built Rate us Contact us model ISSUE #70
  app/page.tsx
  components/landing-page/ContactRateUs.tsx
  public/customer-service.jpg
Labels: gssoc-ext, hacktoberfest-accepted, level2

#146 Added blog frontend and backend
  app/(blog)/blog/page.tsx
  app/api/blog/route.ts
  app/layout.tsx
  components/blog/BlogCard.tsx
  components/blog/Update_Card.tsx
  components/blog/blog-context/BlogContext.tsx
  components/blog/ui/Button.tsx
  components/landing-page/Navbar.tsx
  lib/config.ts
  models/Blog.model.ts
  models/User.model.ts
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#170 pop-up for gemini posts with dynamic features
  app/(root)/dashboard/page.tsx
  components/shared/Popup.tsx
  components/shared/Sidebar.tsx
  components/ui/card.tsx
  components/ui/select.tsx
  components/ui/slider.tsx
  components/ui/toggle-group.tsx
  components/ui/toggle.tsx
  lib/gemini.ts
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#147 Optimize Dockerfile with Multi-Stage Build
  Dockerfile
Labels: gssoc-ext, hacktoberfest-accepted, level1

#178 UI fix: change this misalignments #150
  components/landing-page/Footer.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1
